BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'vertical'
        id: entries_box
        cols: 1
        orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: 0.2
        Button:
            text: "Create Widgets"
            on_release: app.create_widgets()
        Button:
            text: "Clear Widgets!"
            on_release: app.clear_all()